name: Publish Docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: nuwcdivnpt/stig-manager-auth
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract Keycloak version
        id: keycloak-version
        run: |
          KEYCLOAK_VERSION=$(grep -oP 'FROM quay.io/keycloak/keycloak:\K[0-9.]+' Dockerfile)
          echo "version=$KEYCLOAK_VERSION" >> $GITHUB_OUTPUT
          echo "Found Keycloak version: $KEYCLOAK_VERSION"
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_ORG_OWNER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ORG_OWNER_PW }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push standard image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            REALM_FILE=import_realm.json
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.keycloak-version.outputs.version }}
      - name: Build and push dev image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            REALM_FILE=import_realm_dev.json
          tags: |
            ${{ env.IMAGE_NAME }}:dev-latest
            ${{ env.IMAGE_NAME }}:dev-${{ steps.keycloak-version.outputs.version }}